insert into paketsoals(detail) values("matematika");
insert into paketsoals(detail) values("bahasa indonesia");

insert into soals(id_paketsoal,pertanyaan,pilihan1,pilihan2,pilihan3,pilihan4,jawabanbenar) values(1,"Ada 10 buku. 8 buku bersampul coklat. Persentase buku bersampul coklat adalah ", "60%", "80%", "70%", "50", 2);
insert into soals(id_paketsoal,pertanyaan,pilihan1,pilihan2,pilihan3,pilihan4,jawabanbenar) values(1,"Bentuk persen dari 3,5 adalah  ", "35%", "350%", "3,500%", "3,5%", 2);
insert into soals(id_paketsoal,pertanyaan,pilihan1,pilihan2,pilihan3,pilihan4,jawabanbenar) values(1,"Pecahan 0,75 bila diubah menjadi pecahan biasa adalah  ", "3/4", "2/3", "4/5", "1/2", 1);

insert into soals(id_paketsoal,pertanyaan,pilihan1,pilihan2,pilihan3,pilihan4,jawabanbenar) values(2,"Pertandingan sepakbola antara PSS melawan Persebaya berakhir dengan kemenangan Persebaya. Suasana pertandingan berlangsung sangat meriah. Para suporter telah membanjiri Stadion Maguwoharjo sebelum pertandingan dimulai. Mereka saling menjaga diri untuk tidak membuat keributan sampai pertandingan usai. Makna kata suporter dalam paragraf tersebut adalah  ", "penonton", "peminat", "pendukung", "pemirsa", 3);
insert into soals(id_paketsoal,pertanyaan,pilihan1,pilihan2,pilihan3,pilihan4,jawabanbenar) values(2,"Bertani jagung dimulai dengan menanam bijinya. Setelah tiga sampai empat hari bakal tanaman akan muncul di permukaan tanah. Petani dapat memanen jagung setelah tanaman berusia tiga setengah bulan. Itulah tahapan petani dalam menanam jagung. Ide pokok paragraf tersebut adalah ", "teknik bertani jagung", "tahapan bertani jagung", "awal mula bertani jangung", "usia jagung dipanen", 2);
insert into soals(id_paketsoal,pertanyaan,pilihan1,pilihan2,pilihan3,pilihan4,jawabanbenar) values(2,"Air limbah yang berasal dari industri tekstil sangat berbahaya. Air itu mengandung racun. Racun tersebut bisa mengganggu kesehatan manusia. Makna kata limbah pada paragraf tersebut adalah ", "sesuatu yang tidak dipakai", "sisa bahan industri", "sisa proses produksi", "bahan sortiran pabrik", 3);